import { Inter } from "next/font/google";

import { AuthProvider } from "@/context/AuthContext";

import { GoogleOAuthProvider } from "@react-oauth/google";
import "bootstrap-icons/font/bootstrap-icons.css";

import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from '../components/BootstrapClient';

import "./globals.css";
import Head from "next/head";
import Globalnotifier from "@/components/globalNotifier/globalnotifier";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
          <AuthProvider>
            <Globalnotifier />
            <Header />
            {/* ✅ GLOBAL SOCKET LISTENER */}
            
            {children}
            <BootstrapClient />
            <Footer />
          </AuthProvider>
        </GoogleOAuthProvider >
      </body>
    </html>
  );
}
